In [21]:
import pandas as pd
from collections import Counter
from sklearn import preprocessing
import numpy as np

In [22]:
df = pd.read_pickle('../data/processed_all_v1_1.pkl')

In [23]:
df.dropna(axis=0, how='any',inplace = True)

## 1. data 형변환


In [24]:
int_list = ['avgDecodingTime', 'bufferedDuration', 'currentPosition', 'estimatedBandwidth', 'fragmentSum.bitrate',
       'fragmentSum.downloadTime', 'fragmentSum.duration',
       'fragmentSum.fragmentIndex', 'fragmentSum.size', 'frameDropped',
       'licenseInfo.elapsedTime', 'maxDecodingTime',         
       'position',   'qualityChangedCount','timestamp',
       'bufferingTime']

In [25]:
categorical_list = [ 'device','errorCode','licenseInfo.drmSystem', 'networkErrors','networkInfo.carrier.mnc',
                    'networkInfo.type','content_type' ]

In [26]:
for i in df.columns:
    if i in int_list:
        print(i)
        df[i] = df[i].astype(int)
    elif i in categorical_list:
        
        df[i] = df[i].astype('category')
        

avgDecodingTime
bufferedDuration
currentPosition
estimatedBandwidth
fragmentSum.bitrate
fragmentSum.downloadTime
fragmentSum.duration
fragmentSum.fragmentIndex
fragmentSum.size
frameDropped
licenseInfo.elapsedTime
maxDecodingTime
position
timestamp
qualityChangedCount
bufferingTime


In [27]:
cols = df.columns.tolist()
cols

['avgDecodingTime',
 'bufferedDuration',
 'currentPosition',
 'device',
 'errorCode',
 'estimatedBandwidth',
 'fragmentSum.bitrate',
 'fragmentSum.downloadTime',
 'fragmentSum.duration',
 'fragmentSum.fragmentIndex',
 'fragmentSum.size',
 'frameDropped',
 'licenseInfo.drmSystem',
 'licenseInfo.elapsedTime',
 'maxDecodingTime',
 'networkErrors',
 'networkInfo.carrier.mnc',
 'networkInfo.type',
 'position',
 'sessionId',
 'timestamp',
 'qualityChangedCount',
 'content_type',
 'bufferingTime']

In [28]:
cols = cols[4:] + cols[:4]
cols

['errorCode',
 'estimatedBandwidth',
 'fragmentSum.bitrate',
 'fragmentSum.downloadTime',
 'fragmentSum.duration',
 'fragmentSum.fragmentIndex',
 'fragmentSum.size',
 'frameDropped',
 'licenseInfo.drmSystem',
 'licenseInfo.elapsedTime',
 'maxDecodingTime',
 'networkErrors',
 'networkInfo.carrier.mnc',
 'networkInfo.type',
 'position',
 'sessionId',
 'timestamp',
 'qualityChangedCount',
 'content_type',
 'bufferingTime',
 'avgDecodingTime',
 'bufferedDuration',
 'currentPosition',
 'device']

In [29]:
df = df[cols]
df

errorCode  estimatedBandwidth  fragmentSum.bitrate  \
1           0.0            17514086                    0   
2           0.0            10596452             14785860   
3           0.0            17204800                    0   
4           0.0            33011598             69497432   
6           0.0            46066188                    0   
7           0.0            29910232             39773650   
8           0.0            86279112                    0   
9           0.0            19063058             26146651   
10          0.0            51562580             56606460   
11          0.0            13458398             34141138   
12          0.0            49923260             23703824   
13          0.0            13777338             25297411   
14          0.0            62943000             11884216   
15          0.0            45723464                    0   
16          0.0            50946600                    0   
17          0.0            16236292             35099407   
18          0.0            30158938                    0   
19          0.0           104205000                    0   
20          0.0            89998664                    0   
21          0.0            66791384                    0   
22          0.0            40284572              6255458   
23          0.0            80715832            106455214   
24          0.0            49529664                    0   
25          0.0            38532444             58666860   
26          0.0            74578832                    0   
27          0.0           104829576                    0   
28          0.0            19167538                    0   
29          0.0             7196277             13380660   
30          0.0            62792760                    0   
31      -1004.0                  -1                    0   
...         ...                 ...                  ...   
25011       0.0            65991252                    0   
25012       0.0            23087448              1470844   
25015       0.0             4953144              2946658   
25018       0.0            33182456             14788852   
25019       0.0            39924976                    0   
25020       0.0            50524660                    0   
25021       0.0            14445894             12381344   
25022       0.0            56051000                    0   
25024 -100702.0                  -1                    0   
25026       0.0           152022400                    0   
25027       0.0            28660820                    0   
25028 -100702.0                  -1                    0   
25029       0.0            40886616                    0   
25030       0.0            31528236                    0   
25031       0.0             7601181              5928888   
25033       0.0            36065392                    0   
25034       0.0            21308924             11358072   
25035       0.0            54294456             34526345   
25036       0.0            77387152             92742318   
25037       0.0            35027596                    0   
25038       0.0            29386222                    0   
25039       0.0            13461647                    0   
25040       0.0            37724572                    0   
25042       0.0            27724800             23466139   
25043       0.0            11572248             14384065   
25044       0.0            46548968                    0   
25045       0.0           244090672                    0   
25046       0.0            25274956                    0   
25047       0.0           133984000             79488650   
25048       0.0            41405064                    0   

       fragmentSum.downloadTime  fragmentSum.duration  \
1                             0                     0   
2                          4258                 39860   
3                             0                     0   
4                          9481                113145   


In [30]:
df.to_pickle('../data/typed_all_v1_2.pkl')

## 2.라벨 분리

In [32]:
df = pd.read_pickle('../data/typed_all_v1_2.pkl')

In [33]:
x_data = df.iloc[:, 1:].as_matrix()
y_data = df.iloc[:, 0].as_matrix().reshape(-1, 1)
y_data.shape, x_data.shape

/home/centos/anaconda3/envs/dev/lib/python3.5/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
/home/centos/anaconda3/envs/dev/lib/python3.5/site-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


((18663, 1), (18663, 23))

In [34]:
y_data

array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])

In [43]:
np.unique(y_data)

array([ -2.14748365e+09,  -1.01416000e+05,  -1.00874000e+05,
        -1.00870000e+05,  -1.00859000e+05,  -1.00702000e+05,
        -2.00500000e+03,  -1.00400000e+03,  -1.00200000e+03,
        -3.80000000e+01,  -1.20000000e+01,   0.00000000e+00])

## Decision Tree

In [35]:
from sklearn import preprocessing # Min-Max Standardzation

min_max_scaler = preprocessing.MinMaxScaler()
x_data = min_max_scaler.fit_transform(x_data)

import numpy as np 

training_idx = np.random.randint(y_data.shape[0], size=int(y_data.shape[0] * 0.8))
test_idx = np.random.randint(y_data.shape[0], size=int(y_data.shape[0] * 0.2))

x_train, x_test = x_data[training_idx,:], x_data[test_idx,:]
y_train, y_test = y_data[training_idx,:], y_data[test_idx,:]

x_train.shape, x_test.shape

/home/centos/anaconda3/envs/dev/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


((14930, 23), (3732, 23))

In [44]:
np.unique(y_train) 

array([ -2.14748365e+09,  -1.00874000e+05,  -1.00870000e+05,
        -1.00859000e+05,  -1.00702000e+05,  -2.00500000e+03,
        -1.00400000e+03,  -1.00200000e+03,  -3.80000000e+01,
         0.00000000e+00])

In [45]:
np.unique(y_test)

array([ -1.01416000e+05,  -1.00874000e+05,  -1.00870000e+05,
        -1.00859000e+05,  -1.00702000e+05,  -2.00500000e+03,
        -1.00400000e+03,  -1.00200000e+03,  -3.80000000e+01,
         0.00000000e+00])

In [36]:
from sklearn import tree
from sklearn import metrics
qoe_tree = tree.DecisionTreeClassifier(criterion='gini', splitter='random', max_depth=5)
qoe_tree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='random')

In [37]:
y_pred_tr =qoe_tree.predict(x_test)
print('Accuracy: %.2f' % metrics.accuracy_score(y_test, y_pred_tr))

Accuracy: 0.96


In [38]:
print(metrics.classification_report(y_test, y_pred_tr))

              precision    recall  f1-score   support

   -101416.0       0.00      0.00      0.00         1
   -100874.0       0.00      0.00      0.00         4
   -100870.0       0.00      0.00      0.00         3
   -100859.0       0.00      0.00      0.00         1
   -100702.0       0.00      0.00      0.00        90
     -2005.0       0.00      0.00      0.00        11
     -1004.0       1.00      0.90      0.95        10
     -1002.0       0.67      0.40      0.50         5
       -38.0       0.00      0.00      0.00        53
         0.0       0.96      1.00      0.98      3554

   micro avg       0.96      0.96      0.96      3732
   macro avg       0.26      0.23      0.24      3732
weighted avg       0.91      0.96      0.93      3732



/home/centos/anaconda3/envs/dev/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
