In [7]:
import tensorflow as tf

In [8]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 97., 90.], 
          [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [9]:
hypothesis = tf.matmul(X, W) +b

In [10]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(2001):
    cost_val, hy_val, _ =sess.run(
    [cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  109976.0 
Prediction:
 [[-132.4065094 ]
 [-177.73950195]
 [-160.01116943]
 [-182.94854736]
 [-137.64903259]]
100 Cost:  97.9231 
Prediction:
 [[ 159.93133545]
 [ 174.37913513]
 [ 193.85882568]
 [ 194.50575256]
 [ 131.06350708]]
200 Cost:  90.4899 
Prediction:
 [[ 159.54716492]
 [ 174.78921509]
 [ 193.39295959]
 [ 194.53009033]
 [ 131.52633667]]
300 Cost:  83.6315 
Prediction:
 [[ 159.17811584]
 [ 175.18312073]
 [ 192.94538879]
 [ 194.5536499 ]
 [ 131.9707489 ]]
400 Cost:  77.3033 
Prediction:
 [[ 158.82362366]
 [ 175.56150818]
 [ 192.51538086]
 [ 194.57644653]
 [ 132.39749146]]
500 Cost:  71.4642 
Prediction:
 [[ 158.48309326]
 [ 175.92497253]
 [ 192.10221863]
 [ 194.598526  ]
 [ 132.80725098]]
600 Cost:  66.0764 
Prediction:
 [[ 158.15600586]
 [ 176.27415466]
 [ 191.70529175]
 [ 194.61991882]
 [ 133.20074463]]
700 Cost:  61.1051 
Prediction:
 [[ 157.84182739]
 [ 176.60955811]
 [ 191.32388306]
 [ 194.64064026]
 [ 133.57853699]]
800 Cost:  56.5182 
Prediction:
 [[ 157.5400238 ]

<hr>


In [13]:
import numpy as np

In [14]:
xy = np.loadtxt('../data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [15]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [16]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [17]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [18]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [20]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [21]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  14035.9 
Prediction:
 [[ 52.59329605]
 [ 42.62760544]
 [ 52.53070068]
 [ 57.65174103]
 [ 27.12306213]
 [ 18.46273041]
 [ 49.73683548]
 [ 46.63913345]
 [ 35.70299149]
 [ 32.3366394 ]
 [ 41.32823181]
 [ 31.89825249]
 [ 53.38278961]
 [ 42.35850525]
 [ 46.955513  ]
 [ 45.60972595]
 [ 33.40688705]
 [ 64.66159058]
 [ 53.99206543]
 [ 50.66408157]
 [ 55.13383865]
 [ 41.80864334]
 [ 54.18396378]
 [ 51.14244461]
 [ 47.1409874 ]]
100 Cost:  74.2166 
Prediction:
 [[ 163.30467224]
 [ 176.38615417]
 [ 183.96194458]
 [ 200.86097717]
 [ 129.24981689]
 [  93.9464798 ]
 [ 156.84414673]
 [ 125.89596558]
 [ 160.95698547]
 [ 148.57032776]
 [ 144.65489197]
 [ 134.1136322 ]
 [ 189.10980225]
 [ 155.1335907 ]
 [ 154.6665802 ]
 [ 181.3462677 ]
 [ 140.94004822]
 [ 193.08460999]
 [ 183.27032471]
 [ 166.27497864]
 [ 180.8086853 ]
 [ 167.31640625]
 [ 173.92614746]
 [ 162.62269592]
 [ 185.62440491]]
200 Cost:  69.8404 
Prediction:
 [[ 162.94946289]
 [ 176.62826538]
 [ 183.85025024]
 [ 200.80619812]
 [ 129.5

1900 Cost:  27.8755 
Prediction:
 [[ 158.55787659]
 [ 179.75050354]
 [ 182.54148865]
 [ 200.07151794]
 [ 133.44389343]
 [  99.26385498]
 [ 154.83131409]
 [ 122.14840698]
 [ 167.12864685]
 [ 156.76934814]
 [ 144.64216614]
 [ 138.39247131]
 [ 187.03349304]
 [ 152.94216919]
 [ 154.08274841]
 [ 184.64179993]
 [ 140.75102234]
 [ 189.04447937]
 [ 179.77404785]
 [ 162.30131531]
 [ 179.48205566]
 [ 170.62779236]
 [ 171.67732239]
 [ 156.35986328]
 [ 187.33508301]]
2000 Cost:  26.604 
Prediction:
 [[ 158.37509155]
 [ 179.88716125]
 [ 182.49075317]
 [ 200.03793335]
 [ 133.61872864]
 [  99.46768951]
 [ 154.73825073]
 [ 121.97397614]
 [ 167.36540222]
 [ 157.06829834]
 [ 144.63650513]
 [ 138.55238342]
 [ 186.96546936]
 [ 152.87892151]
 [ 154.0448761 ]
 [ 184.76808167]
 [ 140.77519226]
 [ 188.86387634]
 [ 179.65089417]
 [ 162.15641785]
 [ 179.41644287]
 [ 170.75416565]
 [ 171.57841492]
 [ 156.1368103 ]
 [ 187.41075134]]


In [23]:
print("Your score wiil be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Your score wiil be  [[ 161.39486694]]
Other scores will be  [[ 192.92431641]
 [ 182.3157196 ]]


<hr>

In [25]:
filename_queue = tf.train.string_input_producer(
["../data-01-test-score.csv"], shuffle = False, name = "filename_queue")
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [26]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

In [29]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

In [32]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [34]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [35]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [36]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [37]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [39]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  92367.3 
Prediction:
 [[-130.1955719 ]
 [-159.36547852]
 [-155.52598572]
 [-169.88574219]
 [-121.78010559]
 [ -90.78059387]
 [-127.01592255]
 [ -93.8957901 ]
 [-150.16242981]
 [-140.38114929]
 [-122.71139526]
 [-122.42290497]
 [-160.24803162]
 [-132.66917419]
 [-128.07623291]
 [-161.91947937]
 [-126.62992859]
 [-152.13696289]
 [-152.24887085]
 [-135.97792053]
 [-149.22994995]
 [-149.77651978]
 [-141.88937378]
 [-130.22717285]
 [-164.50508118]]
100 Cost:  16.6587 
Prediction:
 [[ 155.41212463]
 [ 184.09571838]
 [ 182.789505  ]
 [ 198.63865662]
 [ 140.15113831]
 [ 102.46534729]
 [ 148.89376831]
 [ 110.720047  ]
 [ 170.95930481]
 [ 157.2341156 ]
 [ 143.09396362]
 [ 139.77738953]
 [ 189.20703125]
 [ 157.73823547]
 [ 149.13774109]
 [ 186.66529846]
 [ 149.91418457]
 [ 178.98449707]
 [ 180.86610413]
 [ 162.0736084 ]
 [ 174.31880188]
 [ 172.49560547]
 [ 166.55213928]
 [ 157.56613159]
 [ 191.38891602]]
200 Cost:  15.7892 
Prediction:
 [[ 155.29350281]
 [ 184.13092041]
 [ 182.7268219 ]


1800 Cost:  8.60788 
Prediction:
 [[ 153.9949646 ]
 [ 184.48925781]
 [ 182.02557373]
 [ 198.67593384]
 [ 140.25476074]
 [ 104.12729645]
 [ 149.6255188 ]
 [ 112.18469238]
 [ 172.87521362]
 [ 161.11721802]
 [ 143.53123474]
 [ 141.46687317]
 [ 187.56445312]
 [ 155.27011108]
 [ 150.2822113 ]
 [ 187.69946289]
 [ 147.15859985]
 [ 179.92623901]
 [ 178.83895874]
 [ 160.19050598]
 [ 175.16888428]
 [ 173.57904053]
 [ 166.93702698]
 [ 154.14337158]
 [ 191.05805969]]
1900 Cost:  8.40929 
Prediction:
 [[ 153.94223022]
 [ 184.50219727]
 [ 181.99621582]
 [ 198.67810059]
 [ 140.25540161]
 [ 104.1893158 ]
 [ 149.65647888]
 [ 112.24638367]
 [ 172.94670105]
 [ 161.26570129]
 [ 143.54872131]
 [ 141.53086853]
 [ 187.50048828]
 [ 155.17321777]
 [ 150.32846069]
 [ 187.73808289]
 [ 147.04855347]
 [ 179.96728516]
 [ 178.76080322]
 [ 160.11851501]
 [ 175.20399475]
 [ 173.61962891]
 [ 166.95429993]
 [ 154.01168823]
 [ 191.04342651]]
2000 Cost:  8.22709 
Prediction:
 [[ 153.89199829]
 [ 184.514328  ]
 [ 181.96812